name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: "self-hosted"
    steps:
    - uses: actions/checkout@v2
    - name: Building image
      run: docker build . -t vepay-demo:latest --target prod
    - name: Stop container
      run: docker stop vepay-demo && docker rm vepay-demo || true
    - name: Start container
      run: docker run -p 127.0.0.1:30110:80 --name vepay-demo -d vepay-demo:latest
